alias p="pnpm"
alias d="pnpm dev"
alias e="pnpm e2e --quick"
alias bs="pnpm build && pnpm start"
alias be="pnpm build && pnpm e2e --quick"
alias eu="pnpm e2e --update"
alias ef="pnpm e2e --full"
alias efu="pnpm e2e --full --update"
